name: CI/CD Pipeline Completo

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar testes
        run: pytest

      - name: Gerar relatório de testes
        run: echo "Testes executados com sucesso" > relatorio.txt

      - name: Salvar artifact de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: relatorio.txt

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar pacote do projeto
        run: zip -r projeto.zip src/

      - name: Salvar artifact do build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: projeto.zip


  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Baixar artifact do build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Simular deploy
        run: |
          mkdir deploy
          mv projeto.zip deploy/
          echo "Deploy realizado com sucesso!"

  notify:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Notificação final
        run: |
          echo "Pipeline finalizado com sucesso!"
          echo "Notificação enviada para: $EMAIL_DESTINO"
        env:
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}