name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar testes
        run: PYTHONPATH=. pytest

      - name: Salvar resultado dos testes
        uses: actions/upload-artifact@v4
        with:
            name: resultados-testes
            path: .

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - run: echo "Build OK"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: echo "Deploy OK"

  notify:
    runs-on: ubuntu-latest
    needs: [test, build, deploy]

    steps:
    - name: Notificação
      run: echo "Pipeline finalizado com sucesso"